build:
    environment:
        php: '7.2'
        mysql: false
        mongodb: false
        postgresql: false
        redis: false
        timezone: 'Europe/London'
    tests:
        override:
            - php-scrutinizer-run
            -
                command: 'vendor/bin/phpunit --testsuite all --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'php-clover'

build_failure_conditions:
    - 'issues.label("coding-style").new.exists'                       # No new coding style issues allowed
    - 'issues.label("bug").new.exists'                                # No new bugs
    - 'issues.label("unused-code").new.exists'                        # No unused code
    - 'issues.severity(>= MAJOR).new.exists'                          # New issues of major or higher severity
    - 'project.metric_change("scrutinizer.test_coverage", < -0.05)'   # Code Coverage decreased more than .5% from previous inspection

filter:
    excluded_paths:
      - tests/*
      - bin/*
      - vendor/*
